server:
  port: 9091

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://172.17.0.1:8080/auth/realms/bcp/protocol/openid-connect/certs

logging:
  level:
    root: INFO
    com.scg.service: TRACE
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG