server:
  port: 9091

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://sre-keycloak.insidepublicprd.gru.oraclevcn.com:8080/auth/realms/scs/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    '[com.scg.service]': DEBUG
    '[org.springframework.web]': INFO
    '[org.springframework.web.HttpLogging]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.security.oauth2]': DEBUG